// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbp1L4AjmgcMOAs2phPbThpL1YV0oaTHs',
    appId: '1:510704844322:web:3faca0cc03bf12176bd47b',
    messagingSenderId: '510704844322',
    projectId: 'cure-task',
    authDomain: 'cure-task.firebaseapp.com',
    storageBucket: 'cure-task.firebasestorage.app',
    measurementId: 'G-VRM0HW3R1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCArND5NhHq8gypvCSdDnZBlb8g56LhR2w',
    appId: '1:510704844322:android:ee4749cadb32ef576bd47b',
    messagingSenderId: '510704844322',
    projectId: 'cure-task',
    storageBucket: 'cure-task.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZiXCPR5mdF2Xuul-Rap_yrS99KJ_ztuM',
    appId: '1:510704844322:ios:4c4b855f599110d46bd47b',
    messagingSenderId: '510704844322',
    projectId: 'cure-task',
    storageBucket: 'cure-task.firebasestorage.app',
    iosBundleId: 'com.example.cureApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZiXCPR5mdF2Xuul-Rap_yrS99KJ_ztuM',
    appId: '1:510704844322:ios:4c4b855f599110d46bd47b',
    messagingSenderId: '510704844322',
    projectId: 'cure-task',
    storageBucket: 'cure-task.firebasestorage.app',
    iosBundleId: 'com.example.cureApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbp1L4AjmgcMOAs2phPbThpL1YV0oaTHs',
    appId: '1:510704844322:web:0e61f92f67ff95416bd47b',
    messagingSenderId: '510704844322',
    projectId: 'cure-task',
    authDomain: 'cure-task.firebaseapp.com',
    storageBucket: 'cure-task.firebasestorage.app',
    measurementId: 'G-WJQ3YZQW3D',
  );
}
